### ISSUE TITLE
merge codes

### ISSUE THREAD

**Issue by tda21** [BlueFern/envy-you#2]
SO I see that we have merged neuroncoupling into master then someone merged it back . What is the current state because I can't really understand what's happened. What is the state of the master at this point . Is it version 1.1 or is still version 1.0 
In addition shouldn't we call it version 1.0 or 1.1 instead of neuroncoupling. I am confused.

**Comment by c-zakkaroff** [comment]
neuronCoupling branch has been merged with master. neuronCoupling branch can be retired. New features/development should come in new branches. The master branch was tagged with v1.1.
